version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Madrid
  open-pull-requests-limit: 10
  commit-message:
    prefix: "[Dep][npm] "
  #ignore:
    #- dependency-name: "django"
      # For django, ignore all updates for version 3.2.x and 4.x
      #versions: [ "3.2", "4" ]
  labels:
    - dependabot
  reviewers:
    - "aplazame/squad_checkout-frontend/reviewers"
